// <auto-generated />
namespace MesTaches.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tache_Projet_Association : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tache_Projet_Association));
        
        string IMigrationMetadata.Id
        {
            get { return "201702121520503_Tache_Projet_Association"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
